name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at midnight (UTC)
  workflow_dispatch:       # You can run manually anytime

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Matrix Dark Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: "mendajagadeesh"
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%2300FF41&color_dots=%23003B00,%23005A00,%2300FF41,%2300E676,%2300C853

      - name: Push Snake SVG to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
